name: Trigger auto deployment for mycontainerapp3

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/mycontainerapp3-AutoDeployTrigger-8fb74c11-014a-429f-95b6-5c950ed5a4fa.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: cad93519b144acr.azurecr.io
          username: ${{ secrets.MYCONTAINERAPP3_REGISTRY_USERNAME }}
          password: ${{ secrets.MYCONTAINERAPP3_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cad93519b144acr.azurecr.io/mycontainerapp3:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYCONTAINERAPP3_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n mycontainerapp3 -g mateipel_rg_8511 --server cad93519b144acr.azurecr.io --username  ${{ secrets.MYCONTAINERAPP3_REGISTRY_USERNAME }} --password ${{ secrets.MYCONTAINERAPP3_REGISTRY_PASSWORD }}
            az containerapp update -n mycontainerapp3 -g mateipel_rg_8511 --image cad93519b144acr.azurecr.io/mycontainerapp3:${{ github.sha }}
